### ISSUE TITLE
Can not create a new workspace when 1 is already running

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/che-starter#128]
Failure  is on resource limits and both workspaces seems to be killed:

`Error creating: pods "che-ws-dm89d8k9yx96epes-1200552331-" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=2539m,limits.memory=1300Mi, used: limits.cpu=3906m,limits.memory=2000Mi, limited: limits.cpu=4,limits.memory=2Gi`

Most things are aync in openshift so things are just 'marked' for shutdown etc..
Probably need to poll the state before continuing execution [1]
However, if we really need to poll the pod state from openshift  and not workspace state from che-server this becomes complicated...

[1]  https://github.com/redhat-developer/che-starter/blob/master/src/main/java/io/fabric8/che/starter/client/WorkspaceClient.java#L134

**Comment by ibuziuk** [comment]
It might be fixed on che-server side with properties like:

```
che.max.running.workspaces = 1
openshift.single.running.workspace = true
```

NOTE: using the second property is easier since if the number was e.g. 2, then when starting a third we need to decide which of the two running workspaces need to be closed

**Comment by l0rd** [comment]
@ibuziuk what about registering for OpenShift events and waiting for the event of the deletion of the pod?

**Comment by ibuziuk** [comment]
@l0rd I haven't investigated it yet, but from the first glance introducing property is the easiest and most reliable way for fixing this issue. I will also take a look at the deletion event

**Comment by amisevsk** [comment]
This is a tricky problem to solve on the server side, as it would require rewriting code in the not openshift-related codebase. We could do something where we use a property to trigger removal of other workspaces when one is started, but would need to find a way of doing the workspace stop throughout che-server, not just in openshift connector. If it's not awfully difficult, it might be better to do it on the che-starter side.

One question: my understanding was the the memory pool for non-terminating pods was separate from the one for terminating pods. If the first workspace is already stopping, it should be in the terminating state, and so shouldn't have an effect on available memory for the new workspace. Can anyone confirm if that's the case?

**Comment by mlabuda** [comment]
Now with my refactoring, it should be quite easy. I implemented 2 waitings - waitUntilWorkspaceIsRunning and waitUntilWorkspaceIsStopped. To fix this issue, those two methods should be enhanced/improved by kubernetes client calls to OpenShift to check resource state and wait for a specific resource to get to a state. You can see similar functionality done in CheDeploymentConfig class, where I did it for waiting on a started Che server, if it was suspended.

**Comment by sbryzak** [comment]
Here's the pull request, this turned out to be quite simple with Marian's new methods:

https://github.com/sbryzak/che-starter/pull/1

**Comment by mlabuda** [comment]
Hmm I see that you haven't added further kubernetes client calls to OpenShift. I think that the problem was, that in Che it looks like a workspace is stopped, but there is still running/terminating pod and thus a new one cannot start. I though we had to add further kubernetes client calls to OpenShift server in those 2 waiting at the end of methods - first we wait for Che workspace resources, then we periodically check OpenShift server what is the state of resources for the workspace.

**Comment by ibuziuk** [comment]
@sbryzak agree with @mlabuda  
As I recall it was decided to check worksapce state not only via che-server rest API, but also using k8s client, no ?

**Comment by mlabuda** [comment]
The best way would be to fix it in OpenShiftConnector in upstream Che - there should be fixed this through k8 client. Question is, do we have time for that?

**Comment by ibuziuk** [comment]
@mlabuda Angel commented that fixing it on che-server side is tricky (and risky IMO)

**Comment by amisevsk** [comment]
I tried to fix the issue of Che thinking workspaces are stopped when one is still terminating -- the `removeContainer()` method should not return until the workspace is fully terminated. If you use the dashboard and click "stop", you can't restart the workspace until it is fully stopped (since it is still in the `STOPPING` phase) but if you refresh the dashboard page, it will often show that same workspace as stopped. I don't know how this applies to the che-starter side though -- the issue appears to be in Che's management of workspace states. It prevents multiple calls to start, but does not seem to do so for stop.

The full fix -- of not allowing more than one workspace simultaneously -- would be even more involved as we'd need to ensure Che tracks stopping workspaces fully, and also blocks start until all `STOPPING` workspaces have stopped. 

On the openshift-connector branch, we haven't touched workspace lifecycle stuff at all so far, we're currently only making changes in the OpenShift connector plugin.

**Comment by ibuziuk** [comment]
Might be coupled - https://issues.jboss.org/browse/CHE-220
